name: Build macOS App

on: 
  push:
    branches: 
      - main  # or your default branch

jobs:
# MacOs
  build-macos-app:
    name: "Build MacOs App"
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v4
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'  # Specify the Python version

    - name: Install Dependencies
      run: |
          pip install pipenv
          pipenv install pyinstaller
          pipenv install pillow
          pipenv install --dev --deploy --ignore-pipfile

    - name: Build Executable with PyInstaller
      run: |
        pipenv run pyinstaller --noconfirm --onefile -n "my-app" --windowed --icon="assets/icon.ico" app.py
    - name: Create Compressed Archive
      run: |
        cd dist
        tar -czf my-app.tar.gz my-app.app

    - name: List files in dist directory
      run: ls dist
      
    - name: Upload Artifact
      uses: actions/upload-artifact@v4
      with:
        name: macos-app
        path: dist/my-app.tar.gz

    
# Windows
  build-windows-app:
    name: "Build Windows App"
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v4
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'  # Specify the Python version

    - name: Install Dependencies
      run: |
          pip install pipenv
          pipenv install pyinstaller
          pipenv install pillow
          pipenv install pywin32-ctypes
          pipenv install --dev --deploy --ignore-pipfile

    - name: Build Executable with PyInstaller
      run: |
        pipenv run pyinstaller --noconfirm --onefile -n "my-app" --windowed --icon="assets/icon.ico" app.py

    - name: List files in dist directory
      run: ls dist
      
    - name: Upload Artifact
      uses: actions/upload-artifact@v4
      with:
        name: windows-app
        path: dist/my-app.exe
  
#   create-release:
#     name: "Create Release"
#     needs: build-macos-app 
#     runs-on: macos-latest
#     steps:
#         - name: Checkout 
#           uses: actions/checkout@v4
#         - name: Download MacOs App
#           uses: actions/download-artifact@v4
#           with:
#             name: macos-app
#         - name: List files
#           run: ls -R
