name: Build macOS App

on: 
  push:
    branches: 
      - main  # or your default branch

jobs:
  build:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v4
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'  # Specify the Python version

    - name: Install Dependencies
      run: |
        pip install -r requirements.txt
        pip install pyinstaller

    - name: Build Executable with PyInstaller
      run: |
        pyinstaller --noconfirm --onefile -n "my-app" --windowed app.py
    
    - name: List files in dist directory
      run: ls dist
      

    - name: Create Package
      run: |
        mkdir output
        cp dist/my-app output/my-app
        hdiutil create -volname "my-app" -srcfolder output -ov -format UDZO my-app.pkg

    - name: Upload Artifact
      uses: actions/upload-artifact@v3
      with:
        name: macos-app
        path: my-app.pkg
