name: Build macOS App

on: 
  push:
    branches: 
      - main  # or your default branch

jobs:
  build-macos-app:
    name: "Build MacOs App"
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v4
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'  # Specify the Python version

    - name: Install Dependencies
      run: |
        pip install -r requirements.txt
        pip install pyinstaller

    - name: Build Executable with PyInstaller
      run: |
        pyinstaller --noconfirm --onefile -n "my-app" --windowed app.py
    
    - name: Create Compressed Archive
      run: |
        cd dist
        tar -czf my-app.tar.gz my-app.app

    - name: List files in dist directory
      run: ls dist
      
    - name: Upload Artifact
      uses: actions/upload-artifact@v4
      with:
        name: macos-app
        path: dist/my-app.tar.gz
  
  create-release:
    name: "Create Release"
    needs: build-macos-app 
    runs-on: macos-latest
    steps:
        - name: Checkout 
          uses: actions/checkout@v4
        - name: Download MacOs App
          uses: actions/download-artifact@v4
        #   with:
        #     name: macos-app
        - name: List files
          run: ls -R
